# ansible/inventory/hosts.ini
[guacamole_nodes]
node01 ansible_host=192.168.10.90
node02 ansible_host=192.168.10.91
node03 ansible_host=192.168.10.92

[guacamole_nodes:vars]
ansible_user=ansible
ansible_ssh_private_key_file=~/.ssh/Proxmox-Cloudinit
